version: '3.9'

services:
  db:
    image: postgres:12
    networks:
      - new
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    container_name: app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - new
    environment:
      DB_POSTGRES_DSN: "postgres://user:password@db:5432/postgres?sslmode=disable"
      LOG_LEVEL: "debug"
      NUM_WORKERS: 1

networks:
  new:
